name: Build and Deploy

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/**'
      - 'Cargo**'
      - 'src/**/*.rs'

jobs:
  build-and-package:
    runs-on: ubuntu-24.04-arm

    env:
      BUILD_TARGET: aarch64-unknown-linux-musl
      PROJECT: log-stream-gc

    steps:
      - uses: actions/checkout@v4

      - name: Update and Configure Rust
        run: |
          sudo apt-get install -y musl-tools
          rustup target add ${{ env.BUILD_TARGET }}
          rustup update
          rustup component add clippy

      - name: Dump Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Build
        run: cargo build --target ${{ env.BUILD_TARGET }}

      - name: Test
        run: cargo test --target ${{ env.BUILD_TARGET }}

      - name: Lint
        run: cargo clippy --target ${{ env.BUILD_TARGET }} -- -D warnings

      - name: Package
        run: |
          cargo build --release --target ${{ env.BUILD_TARGET }}
          cp target/${{ env.BUILD_TARGET }}/release/lambda bootstrap
          zip -j ${{ env.PROJECT }}.zip bootstrap

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ env.PROJECT }}.zip
          retention-days: 1

  deploy-us-east-1:
    needs: build-and-package

    uses: ./.github/workflows/deploy-lambda.yml
    with:
      aws-region: us-east-1
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      bucket-name: ${{ secrets.AWS_US_EAST_1_BUCKET }}

  deploy-us-east-2:
    needs: build-and-package

    uses: ./.github/workflows/deploy-lambda.yml
    with:
      aws-region: us-east-2
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
      bucket-name: ${{ secrets.AWS_US_EAST_2_BUCKET }}
