name: Build and Deploy

on:
  push:
    branches:
      - main

    paths:
      - '.github/workflows/**'
      - 'Cargo**'
      - 'src/**/*.rs'

jobs:
  build-and-test:
    runs-on: ubuntu-24.04-arm

    permissions:
      id-token: write
      contents: read

    env:
      BUILD_TARGET: aarch64-unknown-linux-musl
      PROJECT: log-stream-gc

    steps:
      - uses: actions/checkout@v4

      - name: Update and Configure Rust
        run: |
          sudo apt-get install -y musl-tools
          rustup target add ${{ env.BUILD_TARGET }}
          rustup update
          rustup component add clippy

      - name: Dump Toolchain Info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Build
        run: cargo build --release --target ${{ env.BUILD_TARGET }}

      - name: Test
        run: cargo test --target ${{ env.BUILD_TARGET }}

      - name: Lint
        run: cargo clippy --target ${{ env.BUILD_TARGET }} -- -D warnings

      - name: Package
        run: |
          cp target/${{ env.BUILD_TARGET }}/release/lambda bootstrap
          zip -j ${{ env.ARTIFACT }}.zip bootstrap

      - name: Configure AWS Credentials (us-east-1)
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT }}.us-east-1
          role-session-name: github-deploy
          aws-region: us-east-1
          unset-current-credentials: true

      - name: Deploy Lambda (us-east-1)
        run: aws --region us-east-1 s3 cp ${{ env.PROJECT }}.zip s3://${{ secrets.AWS_US_EAST_1_BUCKET }}/

      - name: Configure AWS Credentials (us-east-2)
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ env.PROJECT }}.github.us-east-2
          role-session-name: github-deploy
          aws-region: us-east-2
          unset-current-credentials: true

      - name: Deploy Lambda (us-east-2)
        run: aws --region us-east-2 s3 cp ${{ env.PROJECT }}.zip s3://${{ secrets.AWS_US_EAST_2_BUCKET }}/
